FILENAME=agreement
all: 
	make --file=variations/OffSiteBackup/Makefile
	make --file=variations/OffSiteBackupWithFileVersioning/Makefile
	make --file=variations/PasswordManagerWithFileVersioning/Makefile
	make --file=variations/PasswordManager/Makefile
